### ISSUE TITLE
Database Context widget problem

### ISSUE THREAD

**Issue by lqdominguez** [janezkranjc/clowdflows#2]
Hi, I'm trying to use the Database Context widget but I got the next error:

![workflow error](https://cloud.githubusercontent.com/assets/12835848/8093959/194d29ba-0f92-11e5-95af-1ab989556742.png)

This is my workflow
 
![workflow](https://cloud.githubusercontent.com/assets/12835848/8093670/744eb6e6-0f90-11e5-8a60-14c117aedffe.png)

I have "cforange" package activated. What should I do?

**Comment by janezkranjc** [comment]
Hello

Try installing the orange package -

pip install orange

**Comment by lqdominguez** [comment]
thanks for your help
